export enum PartnerType {
  TECHNOLOGY = 'TECHNOLOGY',
  CONSULTANCY = 'CONSULTANCY',
  RESELLER = 'RESELLER',
  INTEGRATION = 'INTEGRATION',
  SECURITY_VENDOR = 'SECURITY_VENDOR',
  COMPLIANCE_FRAMEWORK = 'COMPLIANCE_FRAMEWORK',
  DATA_SOURCE = 'DATA_SOURCE',
  LAW_ENFORCEMENT = 'LAW_ENFORCEMENT',
}

export enum PartnerStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED',
}
